name: Lint code

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint using clang-format
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: clang-format Code Formatter
        uses: IvanLudvig/clang-format-action@v1.0
